### ISSUE TITLE
What is the difference between EPUAP and Wezel krajowy?

### ISSUE THREAD

**Issue by Puliczek** [wzychla/OldMusicBox.ePUAP.Client#2]
What is the difference between EPUAP/Profil zaufany SSO and Wezel krajowy?

Is it the same?

**Comment by wzychla** [comment]
Two completely separate and independent Web SSO providers. 

Historically, EPUAP is the first. It allows you to login with the username/password or delegate the authentication to one of supported banking systems.

Then, Węzeł Krajowy has been developed and it doesn't offer its own user accounts. Instead, it delegates authentication to one of providers and the list of the providers is supposed to be modified in future. At the moment you can authenticate using EPUAP and the Digital Personal ID card (e-dowód).

At technical level both are implemented as SAML2 Identity Providers, however:

- EPUAP uses RSA-based certificates, WK forces ECDA-based certificates
- the SAML2 token returned from EPUAP's ArtifactResolve call contains an atrofic token that must be then used in the **getTpUserInfo** call to obtain name, surname and personal ID; the SAML2 token returned from WK's Artifact Resolve call contains the name, surname and personal ID claims, however the token is encrypted 
- systems that are registered to use EPUAP don't automatically support WK and the other way around - a separate registration procedure is required
- all systems that are used in a public sector are obliged to support WK starting from 2020. EPUAP authentication will no longer be supported for new systems starting from 2021
- EPUAP supports authentication, signing and digital exchanges. WK supports authentication only
- WK is supposed to be integrated with european identity providers in future (so that you could possibly be a foreigner and still use a website integrated with WK)

Hope this helps.

**Comment by wzychla** [comment]
Please drop a note if this can be closed.

**Comment by Puliczek** [comment]
Thank you so much, for the good explanation. It dispelled my doubts. 👍
