### ISSUE TITLE
In ePUAP.Demo/Views/Home/ExternalUploadServlet.cshtml input should be a textarea

### ISSUE THREAD

**Issue by preterer** [wzychla/OldMusicBox.ePUAP.Client#4]
https://github.com/wzychla/OldMusicBox.ePUAP.Client/blob/21f9f94341e902d4ce043842f99221e7cf32c038/OldMusicBox.ePUAP.Demo/Views/Home/ExternalUploadServlet.cshtml#L13

This element should be a textarea to keep newline characters and integrity of signature.

**Comment by wzychla** [comment]
What would be the reason behind preserving a signature of a document that is supposed to be unsigned and signed only when it's sent to the service? Another observation: since some XMLs have associated XSLT with them (like the *Pismo ogólne*), the newlines don't matter at all, it's the transformation that is presented to the user, rather than source XML document.

What I mean then is changing the input to textarea could be instant but I don't quite get the rationale.

Could you please elaborate more on that?

**Comment by wzychla** [comment]
This remark would make sense if someone would insist on uploading an already signed document.

However, ePUAP allows passing anything using this method, even unsigned documents - you are free to post anything to public exchanges and the recipient is obliged to accept and process it. 

This is what the demo presents - a dummy PDF is wrapped in a template of Pismo Ogólne and is uploaded to a given exchange. No signature is necessary here, as the recipient of the PDF will be able to see what **source account** has been used to post the document. The fact that the document is unsigned doesn't make any difference in this demo.

On the other hand, I completely see no point of having this kind of open user interface in an actual business application - an application would rather build a form and post it automatically. The presented UI makes sense only for demonstrational purposes, to show how the external upload servlet API is supposed to be used.

Thanks for your feedback, however, I am closing this.

Note that this method of uploading documents is **not officially supported** and not mentioned in any official documentation known to me.
